name = "frontend"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 2.0.0"
lustre = ">= 4.3.2 and < 5.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
modem = ">= 2.0.1 and < 3.0.0"
shared = { path = "../shared" }
lustre_http = ">= 0.5.2 and < 1.0.0"
decode = ">= 0.2.0 and < 1.0.0"
plinth = ">= 0.4.12 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.5.2 and < 2.0.0"
birdie = ">= 1.2.0 and < 2.0.0"
